export const ADD_INGREDIENTS = 'ADD_INGREDIENTS';
export const DEL_INGREDIENTS = 'DEL_INGREDIENTS';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FECTH_INGREDIENTS_FAILED = 'FECTH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';